-- Use this if you are starting your data collection with metrics version v4
create table rba_login_event
(
    login_id               bigserial,
    username               text                                   not null,
    device_uuid            uuid,
    event_timestamp        timestamp with time zone default now() not null,
    metrics_version        integer,
    nn_score               double precision,
    impossible_travel      boolean                  default false not null,
    human_verified         boolean                  default false not null,
    ip_address             inet,
    focus_changes          integer,
    blur_events            integer,
    click_count            integer,
    key_count              integer,
    avg_key_delay_ms       integer,
    pointer_distance_px    bigint,
    pointer_event_count    integer,
    scroll_distance_px     bigint,
    scroll_event_count     integer,
    time_to_first_key_ms   integer,
    time_to_first_click_ms integer,
    idle_time_total_ms     integer,
    total_session_time_ms  integer,
    active_time_ms         integer,
    input_focus_count      integer,
    paste_events           integer,
    resize_events          integer,
    tz_offset_min          integer,
    language               text,
    platform               text,
    device_memory_gb       integer,
    hardware_concurrency   integer,
    screen_width_px        integer,
    screen_height_px       integer,
    pixel_ratio            double precision,
    color_depth            integer,
    touch_support          boolean,
    webauthn_supported     boolean,
    city                   text,
    country                text,
    asn                    text,
    constraint rba_login_event_pk
        primary key (login_id, username)
);